In [7]:
import numpy as np

arr1 = np.arange(10,51)
print(f"1.{arr1}")

arr2 = np.random.randint(1, 101, size=(3,4))
print(f"2.\n{arr2}")

arr3 = np.eye(3)
print(f"3.\n{arr3}")

arr4 = np.linspace(0, 2*np.pi, 10)
print(f"4.\n{arr4}")

1.[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
2.
[[76 19 14 52]
 [50 75 49 49]
 [24 86 83 21]]
3.
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4.
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [8]:
# 2: 
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
second_row = arr[1, :]
print(f"second row: {second_row}")

element = arr[2, 0]
print(f"element at(3,1):{element}")

greater_than_5 = arr[arr>5]
print(f"elements > 5 : {greater_than_5}")

arr_copy = arr.copy()
arr_copy[arr_copy %2==0] = 0
print(f"after replacing evens: \n{arr_copy}")

col_means = np.mean(arr, axis=0)
print(f"column means: {col_means}")

second row: [4 5 6]
element at(3,1):7
elements > 5 : [6 7 8 9]
after replacing evens: 
[[1 0 3]
 [0 5 0]
 [7 0 9]]
column means: [4. 5. 6.]


In [4]:
# 3:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

element_wise = A*B
print(f"Element-wise multiplication:\n{element_wise}")

matrix_mult = A @ B
print(f"Matrix multiplication:\n{matrix_mult}")

det_A = np.linalg.det(A)
print(f"Determinant of A:{det_A:.2f}")

inv_A = np.linalg.inv(A)
print(f"Inverse of A:\n{inv_A}")

eigenvalues = np.linalg.eigvals(A)
print(f"Eigenvalues of A:{eigenvalues}")

Element-wise multiplication:
[[ 5 12]
 [21 32]]
Matrix multiplication:
[[19 22]
 [43 50]]
Determinant of A:-2.00
Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues of A:[-0.37228132  5.37228132]


In [5]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
col_means = np.mean(data, axis=0)
centered_data = data - col_means
print(f"Centered data:\n{centered_data}")

rows = np.arange(5)
grid = np.tile(rows, (5, 1))
print(f"Grid:\n{grid}")

grid_broadcast = np.arange(5).reshape(1, 5) * np.ones((5, 1))
print(f"Grid (broadcast):\n{grid_broadcast}")

arr = np.random.randint(1, 10, size=(4, 3))
row_sums = np.sum(arr, axis=1, keepdims=True)
normalized = arr / row_sums
print(f"Original:\n{arr}")
print(f"Row sums: {np.sum(arr, axis=1)}")
print(f"Normalized:\n{normalized}")
print(f"New row sums: {np.sum(normalized, axis=1)}")

matrix_4x3 = np.arange(12).reshape(4, 3)
vector = np.array([10, 20, 30])
result = matrix_4x3 + vector
print(f"Matrix:\n{matrix_4x3}")
print(f"Vector: {vector}")
print(f"Result:\n{result}")

Centered data:
[[-4.5 -4.5 -4.5]
 [-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]
 [ 4.5  4.5  4.5]]
Grid:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
Grid (broadcast):
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
Original:
[[9 4 8]
 [2 6 4]
 [6 3 5]
 [2 5 2]]
Row sums: [21 12 14  9]
Normalized:
[[0.42857143 0.19047619 0.38095238]
 [0.16666667 0.5        0.33333333]
 [0.42857143 0.21428571 0.35714286]
 [0.22222222 0.55555556 0.22222222]]
New row sums: [1. 1. 1. 1.]
Matrix:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Vector: [10 20 30]
Result:
[[10 21 32]
 [13 24 35]
 [16 27 38]
 [19 30 41]]


In [6]:
temperatures = np.array([
    [20, 22, 21, 23, 24, 22, 21],
    [15, 16, 15, 17, 18, 16, 15],
    [25, 26, 24, 27, 28, 26, 25]
])

days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

city_avg = np.mean(temperatures, axis=1)
for i, avg in enumerate(city_avg):
    print(f"City {chr(65+i)} average: {avg:.2f}°C")

max_temp_idx = np.argmax(temperatures)
city_idx, day_idx = np.unravel_index(max_temp_idx, temperatures.shape)
print(f"Hottest day: {days[day_idx]} in City {chr(65+city_idx)} at {temperatures[city_idx, day_idx]}°C")

city_std = np.std(temperatures, axis=1)
highest_var_city = np.argmax(city_std)
print(f"City with highest variation: City {chr(65+highest_var_city)} (std: {city_std[highest_var_city]:.2f})")

warmer_days = np.sum(temperatures[0] > temperatures[1])
print(f"City A was warmer than City B on {warmer_days} days")

city_min = np.min(temperatures, axis=1, keepdims=True)
city_max = np.max(temperatures, axis=1, keepdims=True)
normalized_temps = (temperatures - city_min) / (city_max - city_min)
print(f"Normalized temperatures:\n{normalized_temps}")

City A average: 21.86°C
City B average: 16.00°C
City C average: 25.86°C
Hottest day: Fri in City C at 28°C
City with highest variation: City A (std: 1.25)
City A was warmer than City B on 7 days
Normalized temperatures:
[[0.         0.5        0.25       0.75       1.         0.5
  0.25      ]
 [0.         0.33333333 0.         0.66666667 1.         0.33333333
  0.        ]
 [0.25       0.5        0.         0.75       1.         0.5
  0.25      ]]
